name: Daily Backup

on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC
  workflow_dispatch: # manual trigger if needed

jobs:
  run-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install

      - name: Run backup worker
        env:
          DISCORD_BOT_TOKEN: "MTQ4MDUzMjE1OTU1ODE5MzIxNA.Gx6XzE.ZzaCcjIm7s9a_SrFVdbxDIb_ISrrs1QT39hkQg"
          DISCORD_CHANNEL_ID: "1480532022928871610"
        run: node index.mjs
